project:
  name: quickstart-armory-spinnaker
  shorten_stack_name: true
  template: templates/tm-new-vpc-bastion-eks-mysql-v6.yaml
  parameters:
    RemoteAccessCIDR: --overridden--
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  package_lambdas: true
  s3_bucket: ''

tests:
    armory-3az-defaults:
      parameters:
        AvailabilityZones: $[taskcat_genaz_3]
        NumberOfAZs: 3
        EKSPublicAccessEndpoint: Enabled
        ProvisionBastionHost: Disabled
        DBUserPassword: --overridden--
	DBMasterUserPassword: --overridden--
      regions:
      - us-east-1
