project:
  name: quickstart-eks-gitlab
  shorten_stack_name: true
  template: templates/spinnaker-entrypoint-new-vpc.template.yaml
  parameters:
    KeyPairName: --overridden--
    RemoteAccessCIDR: 127.0.0.1/32
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
    QSS3KeyPrefix: quickstart-eks-gitlab/
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  s3_bucket: ''

tests:
    deploy-in-3az-with-defaults:
      parameters:
        AvailabilityZones: $[taskcat_genaz_3]
        NumberOfAZs: 3
        EKSPublicAccessEndpoint: Enabled
        ProvisionBastionHost: Disabled
        DBUserPassword: 'Ae6ii5fcckj4ddi0t!'
      regions:
      - us-east-1
