AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  KubeClusterName:
    Default: ""
    Type: String
Resources:
  SpinnakerOpDeployment:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName 
      Namespace: "spinnaker-operator"
      Url: https://raw.githubusercontent.com/mcgonagle/qas/main/operator.yaml
  SpinnakerService:
    Type: "AWSQS::Kubernetes::Resource"
    Properties:
      ClusterName: !Ref KubeClusterName 
      Namespace: "spinnaker"
      Url: https://raw.githubusercontent.com/mcgonagle/qas/main/spinnaker.yaml
    DependsOn: SpinnakerOpDeployment