AWSTemplateFormatVersion: '2010-09-09'
Description: Deploy Armory Spinnaker to and existing EKS Cluster (qs-1rorsilnk).
Metadata:
  QuickStartDocumentation:
    EntrypointName: "Launch into an existing EKS cluster"
    Order: Index c
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - NumberOfAZs
      - AvailabilityZones
      - VPCID
      - VPCCIDR
      - PrivateSubnet1ID
      - PrivateSubnet2ID
      - PrivateSubnet3ID
      - PublicSubnet1ID
      - PublicSubnet2ID
      - PublicSubnet3ID
      - RemoteAccessCIDR
    - Label:
        default: Amazon EC2 configuration
      Parameters:
      - KeyPairName
    - Label:
        default: EKS configuration
      Parameters:
      - NodeInstanceType
      - NumberOfNodes
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - QSS3BucketName
      - QSS3KeyPrefix
      - QSS3BucketRegion
      - ConfigSetName
      - PerAccountSharedResources
      - PerRegionSharedResources
    - Label:
        default: Configures the KubeSphere system and pluggable components
      Parameters:
      - KubeSphereConsolePassword
      - Openpitrix
      - Devops
      - Servicemesh
      - Notification
      - Alerting
      - Auditing
      - Logging
      - Events
      - Multicluster
      - Networkpolicy
      - MetricsServer
    - Label:
        default: Amazon EC2 configuration
      Parameters:
        - ProvisionBastionHost
    ParameterLabels:
      AvailabilityZones:
        default: Availability Zones
      NumberOfAZs:
        default: Number of Availability Zones
      KeyPairName:
        default: SSH key name
      QSS3BucketRegion:
        default: Quick Start S3 bucket region
      PublicSubnet1ID:
        default: Public subnet 1 ID
      PublicSubnet2ID:
        default: Public subnet 2 ID
      PublicSubnet3ID:
        default: Public subnet 3 ID
      PrivateSubnet1ID:
        default: Private subnet 1 ID
      PrivateSubnet2ID:
        default: Private subnet 2 ID
      PrivateSubnet3ID:
        default: Private subnet 3 ID
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix
      RemoteAccessCIDR:
        default: Allowed external access CIDR
      VPCID:
        default: VPC ID
      VPCCIDR:
        default: VPC CIDR
      NodeInstanceType:
        default: Node instance type
      NumberOfNodes:
        default: Number of nodes
      KubeSphereConsolePassword:
        default: KubeSphereConsolePassword
      Openpitrix:
        default: Openpitrix
      Devops:
        default: Devops
      Servicemesh:
        default: Servicemesh
      Notification:
        default: Notification
      Alerting:
        default: Alerting
      Logging:
        default: Logging
      Auditing:
        default: Auditing
      Events:
        default: Events
      Multicluster:
        default: Multicluster
      Networkpolicy:
        default: Networkpolicy
      MetricsServer:
        default: MetricsServer
      ConfigSetName:
        default: ConfigSetName
      PerAccountSharedResources:
        default: Per-account shared resources
      PerRegionSharedResources:
        default: Per region shared resources
      ProvisionBastionHost:
        default: Provision bastion host
Resources:
